name: coco
description: coco makes console colourful
version: 1.0.3
repository: https://github.com/twing-media/coco
homepage: https://github.com/twing-media

environment:
  sdk: '>=2.19.0-444.2.beta <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
